nginx:
  port: 80
  targetPort: 80
  replicaCount: 1
  image: nginx:1.23
  
client:
  port: 7725
  targetPort: 7725
  replicaCount: 1
  image: client:v1.0.0

server:
  port: 7726
  targetPort: 7726
  replicaCount: 1
  image: server:v1.0.0

db:
  port: 27017
  targetPort: 27017
  image: mongo:latest