apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-service
  namespace: {{ .Release.Namespace }}
  labels:
    name: mongo
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.targetPort }}
  selector:
    role: mongo