apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.targetPort }}
  sessionAffinity: ClientIP
