apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nginx-ingress
  namespace: {{ .Release.Namespace }}
spec:
  defaultBackend:
    service:
      name:  {{ .Release.Name }}-nginx-service
      port:
        number: {{ .Values.nginx.port }}