apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-server
  ports:
    - protocol: TCP
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.targetPort }}